### ISSUE TITLE
envelopesApi.listStatus; Error: INVALID_REQUEST_BODY

### ISSUE THREAD

**Issue by RealTayy** [docusign/docusign-node-client#163]
When trying to get current status for envelopes using the node API client, the code below throws this error back 400 - INVALID_REQUEST_BODY:

This error happens when I try to run the following code
```
await envelopesApi.listStatus(accountId, {
  envelopeIds: "ids go here"
},
  ()=> {
});
```
But it will work if I try add the "optional parameter" envelopeIdsRequest like so:
```
await envelopesApi.listStatus(accountId, {
  envelopeIds: "ids go here",
  envelopeIdsRequest: {}
},
  ()=> {
});
```

**Fix suggestions:**
1. Update node-client-api documention to correct state that envelopeIdsRequest is required.

OR

2. Inside of `EnvelopesApi.js` and it's `listStatus()` function:
This line
  ```var postBody = optsOrCallback['envelopeIdsRequest'];```
  Needs to be
  ```var postBody = optsOrCallback['envelopeIdsRequest'] || {};```

**Comment by LarryKlugerDS** [comment]
Hi @RealTayy , 
Thank you for raising this issue.

The [Envelopes::listStatus](https://developers.docusign.com/esign-rest-api/reference/Envelopes/Envelopes/listStatus) call is a `PUT` request, so it can include a request body. Currently, by design, it requires at least a null body of `{}` (when JSON is used).

The reason is that the intention of this call is that an array of envelope ids (potentially very long) will be supplied in the *body* of the call. If you are only interested in specifying a couple of envelope ids, you can use the query parameter (with comma separators), but that's not intended as the usual case. 

Here is an example of specifying an envelope id in the body of the API call. Note that an array is used:

````
let results = await envelopesApi.listStatus(accountId, {
    envelopeIdsRequest: {
        envelopeIds: ["9d8bb903-xxxx-xxxx-xxxx-9e067a226ddc"]
    },
    envelopeIds: 'request_body'})
````
So including at least a null body attribute to the call, `envelopeIdsRequest: {}` is required, as designed.

I agree with you that documenting this issue would be helpful, and I filed  DEVDOCS-1879
I also filed an API enhancement request to not require the null body: EC-2125

**Comment by LarryKlugerDS** [comment]
Also note that you do not need to supply a callback procedure if `await` is used. When await is used, the compiler treats the method as returning a promise with the results (which it does). 

The above code snippet in my comment is tested and works properly.
