### ISSUE TITLE
No way to init client with access token or way to retrieve access token after creating the client

### ISSUE THREAD

**Issue by distracteddev** [docusign/DocuSign-Node-Client#17]
The api documentation seems to encourage saving the access token instead of exchanging the email/password for each request. Is this correct? If so, then the `.client()` function should set the access token on the client itself and the main docusign wrapper should expose a `.clientFromAcessToken` (or some better named function).

**Comment by Whoaa512** [comment]
That is correct, and I am currently trying to think of a clean way to handle this since our coupling of client creation and setting up the methods with the access_token is unnecessarily restrictive.

I've started to scratchpad some ideas in the overhaul-refactor branch but nothing is solidified yet. The tricky part is that every call must be preceded initially by 2 calls, `getLoginInfo` and `getOauthToken`. 

`getLoginInfo` gives you the `accountId` and the `baseUrl`, while `getOauthToken` gives you the `access_token`, all 3 of which are needed to make any call. I'm not sure how to handle this async setup such that user doesn't need to provide those 3 things on every SDK method, since that feels repetitive.

I'd love to hear ideas about the direction you'd like us to go in, or more about how you'd like to use the SDK.

**Comment by distracteddev** [comment]
I'll experiment with some options and let you know what I end up with. My initial thought is to simply have a different .client() method that simply accepts the baseUrl, accountId, and accessToken arguments and then initialized the individual components with that information. 

Basically it would completely bypass the call to auth.getAPIToken()

**Comment by distracteddev** [comment]
Thanks for taking care of this!
