### ISSUE TITLE
Webpack is not supported

### ISSUE THREAD

**Issue by m-czyz** [docusign/docusign-node-client#214]
We're using single file webpack build in AWS Lambda environment and this package is crashing whole build with multiple errors like those:
```
Module not found: 'model/EnvelopesInformation' in /my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/ErrorDetails' in /my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/EventNotification' in /my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950
```

I've tested it with newest version

**Comment by LarryKlugerDS** [comment]
Is your goal to run in Lambda or run on the browser?
(I've mostly heard about using webpack for browser apps.)

The Node SDK doesn't support browser usage at this point, it assumes a Node.js environment.

Webpack is not a supported configuration at this point. If you can identify what the fix is, we can raise it to the engineering team. I'll note that the EventNotification and ErrorDetails models are present in the SDK's source.

**Comment by vmirkin-proag** [comment]
I am having the same problem. I am using webpack to minimize the size of lambdas. 
Are there any plans to support webpack?

**Comment by callumcox** [comment]
> I am having the same problem. I am using webpack to minimize the size of lambdas.
> Are there any plans to support webpack?

I've had the same issue and raised a new issue given this one is closed (you can see the full detail of the problem on #232).  To workaround it I've included the following in my webpack config:

```{
  test: /docusign-esign\/.*\.js$/,
  use: {
    loader: 'imports-loader',
    options: {
      additionalCode: 'var define = false; /* Disable AMD for misbehaving libraries */',
    },
  },
},```

Give something like that a shot and see if it resolves the issue for you :)
