### ISSUE TITLE
Resend / Update Recipient Info

### ISSUE THREAD

**Issue by droppedoncaprica** [docusign/docusign-node-client#44]
It would be nice if we had a way of updating a recipient's name / email to trigger a new email to be sent out through this library.  

[Basic info on how to trigger a resend / update a recipient's info can be found here.](http://stackoverflow.com/questions/21565765/resend-docusign-emails)  It's pretty easy to trigger API-wise, just a matter of setting it up in the library.

Does this sound like something you guys would be willing to add?  It _seems_ fairly simple, though I've not dug in deep into the library to know what implementation would look like.

**Comment by mmallis87** [comment]
We are moving to a brand new NPM package (similar packages are available in Java, C#, ObjC and PHP) that supports all DocuSign eSign API calls (version 2). The new NPM package is available here: https://www.npmjs.com/package/docusign-esign

The new package has a slightly different syntax, that is the same across all programming languages, so it may require a bit of changes in your code but the long term benefits are worth it. So for instance it already comes with the method that you need: "EnvelopesApi.updateRecipients(accountId, envelopeId, recipients, callback)".

The new package source code is still open source and is available under branch DCM-341: https://github.com/docusign/docusign-node-client/tree/DCM-431

If you still want to implement the feature in the old NPM package, feel free to submit a PR.

**Comment by droppedoncaprica** [comment]
So you went from [docusign-node](https://www.npmjs.com/package/docusign-node) to [docusign](https://www.npmjs.com/package/docusign), then finally to [docusign-esign](https://www.npmjs.com/package/docusign-esign)?  I think it's fair to say this is pretty confusing for most users.  

Normally during larger updates, you hide release candidates and beta versions using [proper semantic versioning](http://semver.org/#spec-item-9) rather than creating another npm package altogether.  I can create a PR for this if needed, but ideally these npm package discrepancies should explained in both the `docusign-node` and `docusign` READMEs.  I only happened to stumble upon the `docusign` npm package after searching around (all my code was using the `docusign-node`, which hadn't had some of the latest updates).  

Right now SEO is pointing you towards the `docusign-node` package (which if you don't pay very close attention, seems to be the latest and greatest library from Docusign).

![docusign](https://cloud.githubusercontent.com/assets/1487206/13236054/95bf7c72-d987-11e5-8349-c2fde182f0cc.png)

I know this discussion is outside of the scope of this particular issue (I can create another issue specifically for this npm package business if needed), but man oh man this is super confusing.  Not only that, there hadn't been any obvious discussion about any of these decisions on Github either, which really makes it hard to keep track on what's going on.  I don't think I'm [alone](https://github.com/docusign/docusign-node-client/issues/38) here [either.](https://github.com/docusign/docusign-node-client/issues/32)  (Admittedly one of the issues were opened by a core contributor.)

**Comment by Kampe** [comment]
I second this

**Comment by mmallis87** [comment]
First of all thank you for pinpointing the issue with multiple NPM packages. I agree with you that it is actually confusing. Let me clarify some points here:

- There is no official communication from DocuSign yet about the new Node package. So pointing you to the new package is like a pre-release for you, in order to overcome the missing features in the old package. A proper communication should be released before March 15th. Developers should go to DocuSign Developer Center in order to get the proper versions of the API clients.

- "docusign-node" was just unpublished, so it has disappeared from the screen (was work in progress so we prioritized it after you comment).

- "docusign" package will remain there to support developers who are not ready to move to the new package yet. We keep track of the usage of each, so we will know when to unpublish it as well. In the meanwhile, it will remain deprecated and its readme will refer to the new one (work in progress).

- "docusign-esign" will mention "docusign" package as a "stable version", as the package is not in depth tested yet (it's an open-source project, led by DocuSign, so we rely on the dev community to help in this effort). As the developer community grows, we add more resources to our SDK team and we are constantly growing and hiring: https://www.docusign.com/company/careers

- The new naming conventions will allow us to publish other APIs in multiple languages (till now only the eSign was published to developers)..so more is coming.

**Comment by droppedoncaprica** [comment]
Hooo boy.  So removing the package was probably a pretty big mis-step.  Firstly, it's not going to automatically remove the package from Google results, meaning that anyone clicking on the first npm package that handles Docusign requests will go to an unpublished repo.  Not only that, but if a bad actor realized this, they could have published their own package that did mostly the same thing, only with whatever nefarious code they wanted ran bundled in.

I've done you a solid here and published a replacement npm package so that doesn't happen.  It only includes a README that points towards the correct repo.  If you want control over the README / npm package, send me an email and we'll get it sorted.

Also, thanks for the clarification on what's going on in the future.  Just this time, please don't unpublish the npm package.  :)

**Comment by droppedoncaprica** [comment]
Closing this, as this thread has veered off-course from the original "Resend / Update Recipients" thought.
