### ISSUE TITLE
Broke all of our buillds

### ISSUE THREAD

**Issue by distracteddev** [docusign/docusign-node-client#45]
Hey guys, I understand you wanted to change the name of your node module to `docusign` instead of `docusign-node`, but you cannot simply abuse npm and unpublish all your old versions and not even make them available. 

According to https://github.com/docusign/docusign-node-client/issues/38 you've said you follow semver, which means that 7.0 is not compatible with 6.0. So I cannot even hardlink my services to the version I was using, and our entire organization has QA'd and tested. 

Is there something I'm missing? Is there a reason why all versions < 7 are no longer available on npm?

**Comment by Whoaa512** [comment]
Just pushed & published 19c0b44 on the `6.x` branch. If an older version is needed let me know. 

I'd also point you to read https://github.com/docusign/docusign-node-client/issues/44#issuecomment-187422877 to understand where DocuSign has decided to head with it's client libraries.

As a side note I am no longer the core maintainer of this repo but will still be around for a little bit to chime in on discussions & PRs until the transition to the new generated library is completed.

**Comment by mmallis87** [comment]
@distracteddev I apologize for broking your builds and I would like to know what is the SemVer that you use for our old package "docusign-node", in your package.json?

As mentioned, DocuSign is moving to a brand new package that supports fully our e-signature rest API. So I encourage you to consider exploring the new package an play with it.

**Comment by droppedoncaprica** [comment]
It's not really a semver issue, it's a "we unpublished the module from npm" issue. 

Unfortunately they're really not really following semver either.  Instead of hiding the beta version behind a beta tag and incrementing the major release version after being ready, they are instead putting the beta under a different npm package.  Plus it's up in the air if they'll notify or alter the original `docusign` package to notify new users they should be using `docusign-esign` instead.  

There were comments that suggested that Docusign will have an announcement in their developer center, but let's be real.  No one will be checking that once they have their Docusign implementation feature complete.  I know personally if I monitored the announcements of all the different API's I've implemented at work, I'd get nothing done during the day.

Extra bonus points for having the Github tag and npm versions diverge (`docusign-esign` is on v2.0.0 and the latest `docusign` package is on v8.x.x).  Support requests will be confusing once you guys move forward with this, as you now can't correlate their installed npm version with a Github tag.

Overall I hope once the `docusign-esign` package gets past beta status, you guys merge the changes with a new major version release for `docusign`.

**Comment by Whoaa512** [comment]
I am personally in favor of sticking with the `docusign` name and merging the new beta stuff in as v9.0 BUT the decision makers are real sticklers for keeping the package version the same as the API version.

However I find that unrealistic because our API does not strictly follow semver.

I'd love for you guys to chime in with your opinions since you are the vocal members of the DocuSign Node community and we value your input.

**Comment by droppedoncaprica** [comment]
Personally I'm for keeping all future updates to `docusign` package.  If what's in the `docusign-esign` package is feature-compatible with what's able to be done with the `8.x` version, then there's no real reason to hide it behind an alpha tag either.  The major version bump should mean that most people won't be hit with the different API out of nowhere (unless they are using something like `docusign: *` or similar).

**Comment by mmallis87** [comment]
@distracteddev Can you confirm that your build is working now, after we got the old package back?

**Comment by mmallis87** [comment]
Didn't hear back from the reporter for a long time. Please open a new issue if, by any chance, the issue comes back.
