### ISSUE TITLE
event_notification

### ISSUE THREAD

**Issue by alexpchin** [docusign/docusign-node-client#53]
I'm struggling to receive the status of a contract. It looks like you can do this with a webhook as per https://www.docusign.com/developer-center/recipes/webhook-status however - does this library support this?

**Comment by mmallis87** [comment]
@alexpchin Yes this Node client library supports webhook and here is a fully working sample app that illustrates the use of webhooks with DocuSign: https://github.com/docusign/recipe-010-webhook-node

You can deploy the sample app in Heroku or Azure, or just use the existing Heroku live app: https://ds-webhook-node.herokuapp.com/

Finally, the sample app source code might not be easy to understand, in that case I will be happy to help. Otherwise you can mark this issue as closed.

**Comment by mmallis87** [comment]
@alexpchin any news about this. If I don't hear from you within next days I will have to close the issue. Of course we can reopen it later on if the problem persists.
