### ISSUE TITLE
Prefixing Text Fields 'Tab Label' with \\* has undocumented behavior

### ISSUE THREAD

**Issue by bigorangemachine** [docusign/docusign-node-client#64]
I'm concerned the Asterisk functionality is working incorrectly.  I'm not sure if its on the Node side of docusign or the docusign API backend.

When you have a field like `VerificationNo` and `SecondaryVerificationNo` setup in your document and you use a text field label in this way ```{"tabLabel":"\\*VerificationNo","value":"######"}``` (without sending `SecondaryVerificationNo`) it'll populate both fields with the data provided in `VerificationNo`.  Is this a bug or how its intended?

**Comment by bigorangemachine** [comment]
Hey @docusign?

Is anyone looking into this?

**Comment by Ergin008** [comment]
Hi @bigorangemachine sorry for the delay.  I believe this is working as intended, the way the `\\*` character sequence works is that it acts as a wild card matching ANY string that comes after the sequence, either as a full string or a sub-string.

When you send a tabLabel `\\*VerificationNo` the system will match any and every tab that has `"VerificationNo"` in the name.  Therefore, if you have another tab that has tabLabel `SecondaryVerificationNo` it will also populate this tab since it has `...VerificationNo` in the name.  

Hopefully this clear things up?  

Thanks,
-Ergin

**Comment by chris-fa** [comment]
Hello, is there a way for fill multiple tabs with the same name, without using the wildcard? I'm facing a problem where `Name` and `CompanyName` tabs are being filled with the value set for `Name`

**Comment by LarryKlugerDS** [comment]
Re: is there a way for fill multiple tabs with the same name, without using the wildcard? 

Yes, first list the tabs in the template, then update them individually.

You can list the template's tabs or the envelope's tabs using a method such as [EnvelopeRecipientTabs::list](https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeRecipientTabs/list) -- Note its `include_anchor_tab_locations` query parameter if you're using anchor tabs.

Once you have the entire list of tabs, update the values of just the desired tabs.

**Comment by LarryKlugerDS** [comment]
ps. I apologize for the very slow response to your question. We have re-organized to provide better response times. 

StackOverflow (with the docusignapi tag) is usually better for general API questions.
