### ISSUE TITLE
Where can I find docs for the 2.1.0?

### ISSUE THREAD

**Issue by chris-fa** [docusign/docusign-node-client#80]
Our codebase is somewhat legacy and I'm trying to change from Legacy Header to OAuth without having to update to `3.2.1`. Do you have any available documentation for `2.1.0`?

**Comment by mmallis87** [comment]
@chris-fa I know it would be nice if npmjs.com keep snapshots for each version...Luckily Github does and you can find some documentation in the README of v2.1.0: https://github.com/docusign/docusign-node-client/tree/v2.1.0

**Comment by chris-fa** [comment]
@mmallis87 I did read that docs, I was looking for something more like http://docusign.github.io/docusign-node-client/ but for `2.1.0`.  Specifically because there's no mention of Passport support on `2.1.0`, so I'm wondering whether it's supported, and looking for more docs if any

**Comment by mmallis87** [comment]
We don't update these SDK docs with every release, since the interfaces don't change very often..However we have a plan to have SDK docs in most if not all of our SDKs. Till then, you can checkout branch 2.1.0 and then run "npm run docs", this will generate up-to-date docs into ./docs folder locally.

For you second question, passport is not mandatory for this NPM package/sdk. If you wanna use it with v2.1.0, you can take advantage of [passport-docusign](https://www.npmjs.com/package/passport-docusign) to get OAuth tokens, since we didn't have embedded support for passport. Once you have the token then you can pass it along to the API Client like this: apiClient.addDefaultHeader('Authorization', 'Bearer ' + user.accessToken);

The rest should be the same as usual.
