### ISSUE TITLE
Do we need to pay if we use this Docusign Api or its open source

### ISSUE THREAD

**Issue by praveenmk4** [docusign/docusign-node-client#93]
I would like to use this node module in my code as its exactly fits to my requirement and I would like to know whether its a opensource Api or Do we need to pay as this module using the API's by Docu-esign.Please revert me back on this

**Comment by mmallis87** [comment]
@praveenmk4 glad this SDK is mostly an open-source wrapper around DocuSign API. So in order to use it in a production, where electronic signatures are legally binding, you need to buy an API plan:

Here are the milestones to go live with your integration:
1. Signup for a free Sandbox and build an integration: https://developers.docusign.com/esign-rest-api/guides
3. Purchase an API plan: https://www.docusign.com/products-and-pricing/api-plans
4. Submit to Go Live: https://developers.docusign.com/esign-rest-api/guides/go-live
